<a href="https://colab.research.google.com/github/Leaco92/test-colab/blob/main/Trabajo_Pr%C3%A1ctico(2%C2%AA_Conv_)_Jose_Leandro_Parada_rivera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Seminario<br>
Nombre y Apellidos:  Jose Leandro Parada Rivera <br>
Url: https://github.com/.../03MAIR---Algoritmos-de-Optimizacion---2019/tree/master/SEMINARIO<br>
Problema:
> 1. Sesiones de doblaje <br>

Descripción del problema:(copiar enunciado)


(*) La respuesta es obligatoria





                                        

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en
las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores
de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el
estudio de grabación independientemente del número de tomas que se graben. No es
posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de
manera que se gasto por los servicios de los actores de doblaje sea el menor posible. Los
datos son:
Número de actores: 10
Número de tomas : 30
Actores/Tomas :
1 indica que el actor participa en la toma
0 en caso contrario

(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.




Respuesta

In [ ]:
# Posibilidades sin restricciones = 42'751.800
# Posibilidades con restircciones = 593.751


Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


Respuesta

Se selecciona una estructura de datos de tipo dinámico para dar solución al problema, en este caso se implementa a traves de un árbol de expansión que modela todo el espacio de soluciones y se implementan un par de condiciones que permiten disminuir el espacio de soluciones

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?

(*)¿Es un problema de maximización o minimización?

Respuesta

Función objetivo:

$$\mathrm{Y= x_1+x_2+x_3+x_4+x_5}$$

donde 
$$\mathrm{Y = costo-total}$$ 
$$\mathrm{x_n = coste-de-grabación-por-día}$$

Tipo de problema:

es una función a minimización en donde se busca una solución que proporcione el menor resultado posible teniendo en cuenta las restricciones del problema

Diseña un algoritmo para resolver el problema por fuerza bruta

Respuesta

In [4]:
from google.colab import files 

uploaded = files.upload()

Saving data.csv to data (1).csv


In [9]:
import pandas as pd 
import numpy as np
import io 

df = pd.read_csv(io.BytesIO(uploaded['data.csv']),delimiter=';') 
nmp=df.to_numpy()


#se crea una función que permita seleccionar la primera escena 
def criterios_seleccion_scn1(total_escenas):
  #seleccion de primera escena
  x,i,escenas_dia=0,0,[]
  total_escenas_f=np.delete(total_escenas, 11, axis=1)
  maxValues = sorted(total_escenas_f.max(axis = 1),reverse=True) 
  while x==0:
    if total_escenas_f[i][10]==maxValues[0]:
      x=1
      escenas_dia.append(total_escenas[i])
      total_escenas=np.delete(total_escenas, i, axis=0)
    i+=1
  return escenas_dia,total_escenas

#Se crea una funciona que permita determinar el coste por medio de los actores de la escena
def total_actores_escena(actores,nueva_escena):
  if len(actores) >11:
    actores=np.delete(actores, 11)
    nueva_escena=np.delete(nueva_escena, 11)
  if len(actores) >10:
    actores=np.delete(actores, 10)
    nueva_escena=np.delete(nueva_escena, 10)
  val=np.where(nueva_escena ==1)
  for i in val[0]:
    actores[i]=1
  return actores

#Se crea una función que permita seleccionar el resto de las escena que se deben de realizar en el dia 
def criterios_seleccion_scn(escena,total_escenas,actores):
  #seleccion siguiente escena
  val=np.where(actores == 1)
  mismos,nuevos,siguiente_escena=0,5,0
  for i in range(len(total_escenas)):
    nuevos_act = len(np.setdiff1d(np.where(total_escenas[i] == 1), val))
    mismos_act = len(np.setdiff1d(val, np.where(total_escenas[i] == 1)))
    if len(val[0])-mismos_act > mismos:
      siguiente_escena=i
      mismos=len(val[0])-mismos_act
  escena.append(total_escenas[siguiente_escena])
  actores_f=total_actores_escena(actores,total_escenas[siguiente_escena])
  total_escenas=np.delete(total_escenas, siguiente_escena, axis=0)
  return escena,total_escenas,actores_f

#Se crea una función que permite seleccionar y dividir la escenas por dia y mostras las ecenas totales por dia 
def tomas_dia(total_escenas,max_tomas_dia):
  escenas_totales=[]
  costo_total=0
  tamaño=0
  while tamaño<5:
    for j in range(5):
      escena,total_escenas=criterios_seleccion_scn1(total_escenas)
      actores = total_actores_escena(escena[0],escena[0])
      total_tomas_dia=[]
      total_costos_x_dia=0
      for i in range(1,max_tomas_dia):
        escena,total_escenas,actores = criterios_seleccion_scn(escena,total_escenas,actores)    
      total_tomas_dia.append(escena)
      total_costos_x_dia=sum(actores)
      escenas_totales.append(total_tomas_dia)
      costo_total+=total_costos_x_dia
    tamaño = len(escenas_totales)
  return(escenas_totales,costo_total)


In [10]:
tomas_dia(nmp.copy(),6)

([[[array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 5, 1]),
    array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 4, 6]),
    array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 4, 7]),
    array([ 1,  1,  1,  0,  1,  0,  0,  1,  0,  0,  5, 11]),
    array([ 1,  1,  1,  1,  0,  1,  0,  0,  0,  0,  5, 12]),
    array([ 1,  0,  1,  1,  1,  0,  0,  0,  0,  0,  4, 20])]],
  [[array([1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 4, 4]),
    array([ 1,  1,  0,  0,  0,  0,  1,  0,  0,  0,  3, 15]),
    array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 3, 3]),
    array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 3, 5]),
    array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 3, 9]),
    array([ 1,  0,  0,  1,  1,  0,  0,  0,  0,  0,  3, 13])]],
  [[array([ 1,  1,  0,  0,  0,  1,  0,  0,  1,  0,  4, 10]),
    array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 3, 8]),
    array([ 1,  0,  1,  0,  0,  1,  0,  0,  0,  0,  3, 14]),
    array([ 1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  4, 22]),
    array([ 1,  1,  0,  1,  0,  0,  0,  0,  0,  1,  4, 25]),
    array([ 1,  0,  1,  0,  1,  0,  0,  0,  1,  0,  4, 

Calcula la complejidad del algoritmo por fuerza bruta

Respuesta

In [ ]:
#la complejidad del codigo es de n^3

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

Respuesta

El algoritmo utilizado para mejorar el de fuerza bruta es el de “Backtracking” o “Fuerza bruta”, con la implementación de este algoritmo se redujo la complejidad del sistema de n^3 en el de fuerza bruta a n^2 en el de Backtracking; adicional a esto se logró minimizar aún más la función objetivo del sistema ya que de un costo de 32 en fuerza bruta se disminuyo a un valor de 26 con Backtracking; por ultimo al seleccionar este algoritmo se contemplan una mayor cantidad de soluciones posibles.

In [25]:
df = pd.read_csv(io.BytesIO(uploaded['data.csv']),delimiter=';') 
nmp=df.to_numpy()


# se crea una función de coste para la seleccion de escenas por dia
def funcion_coste(escena,actores,costo_f):
  acc=0
  if len(escena) >11:
    escena=np.delete(escena, 11)
  act=np.where(escena == 1)
  if len(np.union1d(act, actores)) <=costo_f:
    acc=sum(np.union1d(act, actores))
    actores=np.union1d(act, actores)
    return True,actores,acc
  else:
    return False,actores,acc

#se crea una funcion que permite determinar todas las funciones por dia que se pueden generar dadas las condiciones 
def dia_escena(N,total_escenas,escena,costo_f,restricciones=[], solucion=[],actores=[],act=[],m=[]): 
  if len(solucion) == 0:
    solucion = [0 for i in range(N) ]
  for i in total_escenas:
    if escena==0:
      restricciones,actores=[],[]  
    if i[11] not in restricciones:
      solucion[escena] = i
      costo,actores,acc=funcion_coste(solucion[escena],actores,costo_f)
      if costo:        
        if escena == N-1:
          if acc not in act:
            act.append(acc)
            m.extend(solucion)
          restricciones.append(i[11])
          actores=[] 
        else:          
          restricciones.append(i[11])
          dia_escena(N,total_escenas,escena+1,costo_f,restricciones, solucion,actores,act,m)      
  return m 

#Se crea una función que permite elimir las escenas que se seleccionen 
def eliminar_filas(escenas_totales,escenas_dia,n):
  f_eli=[]
  for i in range(n):
    a,_=np.where(escenas_totales[:, -1:12] == escenas_dia[i][11])
    f_eli.append(a[0])
  escenas_totales=np.delete(escenas_totales, (tuple(f_eli)), axis=0)
  return escenas_totales

#Se crea una funcion de coste que permite calcular el coste de la escena total 
def coste_final(costo,coste_max,escena):
  val1,val=0,0
  if escena == 0:
    val+=costo[0]
    val1+=coste_max[0]
  else:
    for i in range(escena):
      val+=costo[i]
      val1+=coste_max[i]
      if costo[i]<coste_max[i]:
        coste_max[i]=costo[i]
  if val<val1:
    return 1,coste_max
  else:
    return 0,coste_max


 #Se crea una función que permite seleccionar y dividir la escenas por dia y mostras las ecenas totales por dia  
def fun_escenas_total(N,costo,escena,escenas_totales,d,total_escenas=[],solucion=[],costo_total=[],costo_max=[]):

  if len(solucion) == 0:
    solucion = [0 for i in range(N) ]
    costo_total = [0 for i in range(N) ]
    costo_max = [100 for i in range(N) ]
  tama=True
  while tama==True:
    if len(escenas_totales)>6:
      escenas_dia =dia_escena(6,escenas_totales,0,costo,restricciones=[],solucion=[0, 0, 0, 0, 0, 0],actores=[],act=[],m=[])
      if len(escenas_dia)>0:
        tama=False
      else:
        costo+=1
    else:
      escenas_dia=escenas_totales
      tama=False
  escenas_dia=np.array_split(escenas_dia,len(escenas_dia)/6)
  for i in escenas_dia:
    costo_total[escena]=costo
    solucion[escena] = i 
    val,costo_max=coste_final(costo_total,costo_max,escena)
    if val==1:
      if sum(costo_total)<sum(costo_max):
        if escena == N-1:
            total_escenas=solucion
            costo_max=costo_total
            return print('costo min=',sum(costo_total),'Matriz de coste', costo_max,'Escenas= ',total_escenas)
        else:     
            escenas_totales=eliminar_filas(escenas_totales,i,N)
            fun_escenas_total(N,4,escena+1,escenas_totales,d,total_escenas,solucion,costo_total,costo_max)


In [26]:
fun_escenas_total(5,4,0,nmp.copy(),5,total_escenas=[],solucion=[],costo_total=[],costo_max=[])

costo min= 26 Matriz de coste [4, 4, 5, 6, 7] Escenas=  [array([[ 0,  0,  1,  1,  1,  0,  0,  0,  0,  0,  3,  2],
       [ 1,  0,  0,  1,  1,  0,  0,  0,  0,  0,  3, 13],
       [ 1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  2, 17],
       [ 1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  2, 19],
       [ 1,  0,  1,  1,  1,  0,  0,  0,  0,  0,  4, 20],
       [ 1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  2, 23]]), array([[ 1,  1,  0,  1,  1,  0,  0,  0,  0,  0,  4,  6],
       [ 1,  1,  0,  1,  1,  0,  0,  0,  0,  0,  4,  7],
       [ 1,  1,  0,  1,  0,  0,  0,  0,  0,  0,  3,  9],
       [ 0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  2, 27],
       [ 1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  2, 28],
       [ 1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  2, 30]]), array([[ 1,  1,  0,  0,  0,  1,  0,  0,  1,  0,  4, 10],
       [ 1,  1,  0,  0,  0,  1,  0,  0,  0,  0,  3,  8],
       [ 1,  0,  1,  0,  0,  1,  0,  0,  0,  0,  3, 14],
       [ 0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  2, 18],
       [ 1,  0,  1,  0,  0,

(*)Calcula la complejidad del algoritmo 

Respuesta

In [ ]:
#la complejidad del codigo es de n^2

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [22]:
import random

escenas = np.zeros((30, 12))
for i in range(len(escenas)):
  val = random.randint(0, 5)
  for j in range(val):
    val1 = random.randint(0, 9)
    while escenas[i][val1] ==1:
      val1 = random.randint(0, 9)
    escenas[i][val1]=1
  escenas[i][10]=val
  escenas[i][11]=i+1

print(escenas)


[[ 0.  1.  0.  0.  0.  1.  1.  0.  1.  0.  4.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  2.  3.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  1.  0.  2.  4.]
 [ 1.  1.  1.  1.  0.  0.  1.  0.  0.  0.  5.  5.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  7.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  2.  8.]
 [ 1.  0.  0.  1.  0.  1.  0.  0.  0.  0.  3.  9.]
 [ 0.  1.  0.  0.  1.  0.  0.  0.  1.  0.  3. 10.]
 [ 1.  0.  1.  0.  1.  0.  0.  0.  1.  1.  5. 11.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1. 12.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 13.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  1.  0.  2. 14.]
 [ 1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  2. 15.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
 [ 1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  3. 17.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 18.]
 [ 0.  0.  0.  0.  1.  1.  1.  0.  1.  1.  5. 19.]
 [ 0.  0.  0.  0.  1.  1.  1.  

Aplica el algoritmo al juego de datos generado

Respuesta

In [24]:
fun_escenas_total(5,4,0,escenas.copy(),5,total_escenas=[],solucion=[],costo_total=[],costo_max=[])

costo min= 27 Matriz de coste [4, 4, 4, 7, 8] Escenas=  [array([[ 0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  4.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  2.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  6.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  7.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 13.]]), array([[ 1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  3.,  9.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  2.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 13.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  2., 15.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 16.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 18.]]), array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1., 12.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,

Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

Respuesta

Para poder avanzar con el estudio del problema es posible implementar un algoritmo de programación dinámica en donde se guarden todos los costos de las diferentes combinaciones y de esta forma poder escoger la mejor solución posible 